version: '3.8'

services:
  web:
    container_name: roshan_api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost, 127.0.0.1, 0.0.0.0
      - DATABASE_URL=sqlite:///db.sqlite3 
    networks:
      - default

# volumes:
#   db_data:  # This will persist the SQLite database in Docker volume if needed

networks:
  default:
    driver: bridge
