# Generated by Django 5.1.3 on 2024-11-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productviewlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductViewLog',
        ),
    ]
